### ISSUE TITLE
Topbar header section

### ISSUE THREAD

**Issue by ganicodes** [ganicodes/spendy-client#2]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Need top bar with as given in screenshot.
<img width="1016" alt="Screenshot 2023-06-05 at 12 02 16 AM" src="https://github.com/ganicodes/spendy-client/assets/84485209/7f3e2977-8726-46ec-a25e-ac232fcc48b6">

**Additional context**
<img width="1309" alt="Screenshot 2023-06-04 at 11 51 36 PM" src="https://github.com/ganicodes/spendy-client/assets/84485209/aac90de8-d7cd-433a-95bc-57669ebe86ae">

**Comment by atultingre** [comment]
feature-added topbar
